//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Implementation.ApplicationServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApplicationServerSoap", Namespace="http://tempuri.org/")]
    public partial class ApplicationServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback KillSelfNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMaSoGCSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CountMaSoGCSOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertDSachSoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteMaSoGCSOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSoGCS_QueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogByNumOfRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogBySubdivisionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getLogByBookIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteByMaSoGCSOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteByLogIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvoiceData_ForCalculationOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInvoiceData_ForCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelInvoiceCalculationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSoGCSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApplicationServer() {
            this.Url = "http://localhost/ApplicationServer/ApplicationServer.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event KillSelfNewCompletedEventHandler KillSelfNewCompleted;
        
        /// <remarks/>
        public event getMaSoGCSCompletedEventHandler getMaSoGCSCompleted;
        
        /// <remarks/>
        public event CountMaSoGCSCompletedEventHandler CountMaSoGCSCompleted;
        
        /// <remarks/>
        public event InsertDSachSoCompletedEventHandler InsertDSachSoCompleted;
        
        /// <remarks/>
        public event DeleteMaSoGCSCompletedEventHandler DeleteMaSoGCSCompleted;
        
        /// <remarks/>
        public event getSoGCS_QueueCompletedEventHandler getSoGCS_QueueCompleted;
        
        /// <remarks/>
        public event getLogByNumOfRecordCompletedEventHandler getLogByNumOfRecordCompleted;
        
        /// <remarks/>
        public event getLogBySubdivisionIDCompletedEventHandler getLogBySubdivisionIDCompleted;
        
        /// <remarks/>
        public event getLogByBookIDCompletedEventHandler getLogByBookIDCompleted;
        
        /// <remarks/>
        public event DeleteByMaSoGCSCompletedEventHandler DeleteByMaSoGCSCompleted;
        
        /// <remarks/>
        public event DeleteByLogIDCompletedEventHandler DeleteByLogIDCompleted;
        
        /// <remarks/>
        public event getInvoiceData_ForCalculationCompletedEventHandler getInvoiceData_ForCalculationCompleted;
        
        /// <remarks/>
        public event getInvoiceData_ForCancelCompletedEventHandler getInvoiceData_ForCancelCompleted;
        
        /// <remarks/>
        public event CancelInvoiceCalculationCompletedEventHandler CancelInvoiceCalculationCompleted;
        
        /// <remarks/>
        public event GetInvoiceCompletedEventHandler GetInvoiceCompleted;
        
        /// <remarks/>
        public event GetSoGCSCompletedEventHandler GetSoGCSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KillSelfNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KillSelfNew(string strMaDViQLy, string strName, string strTenDNhap, string strMaCNang, ref string strTimeStamp, LoaiDoiTuong ObjectType) {
            object[] results = this.Invoke("KillSelfNew", new object[] {
                        strMaDViQLy,
                        strName,
                        strTenDNhap,
                        strMaCNang,
                        strTimeStamp,
                        ObjectType});
            strTimeStamp = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KillSelfNewAsync(string strMaDViQLy, string strName, string strTenDNhap, string strMaCNang, string strTimeStamp, LoaiDoiTuong ObjectType) {
            this.KillSelfNewAsync(strMaDViQLy, strName, strTenDNhap, strMaCNang, strTimeStamp, ObjectType, null);
        }
        
        /// <remarks/>
        public void KillSelfNewAsync(string strMaDViQLy, string strName, string strTenDNhap, string strMaCNang, string strTimeStamp, LoaiDoiTuong ObjectType, object userState) {
            if ((this.KillSelfNewOperationCompleted == null)) {
                this.KillSelfNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKillSelfNewOperationCompleted);
            }
            this.InvokeAsync("KillSelfNew", new object[] {
                        strMaDViQLy,
                        strName,
                        strTenDNhap,
                        strMaCNang,
                        strTimeStamp,
                        ObjectType}, this.KillSelfNewOperationCompleted, userState);
        }
        
        private void OnKillSelfNewOperationCompleted(object arg) {
            if ((this.KillSelfNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KillSelfNewCompleted(this, new KillSelfNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMaSoGCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getMaSoGCS() {
            object[] results = this.Invoke("getMaSoGCS", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getMaSoGCSAsync() {
            this.getMaSoGCSAsync(null);
        }
        
        /// <remarks/>
        public void getMaSoGCSAsync(object userState) {
            if ((this.getMaSoGCSOperationCompleted == null)) {
                this.getMaSoGCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMaSoGCSOperationCompleted);
            }
            this.InvokeAsync("getMaSoGCS", new object[0], this.getMaSoGCSOperationCompleted, userState);
        }
        
        private void OngetMaSoGCSOperationCompleted(object arg) {
            if ((this.getMaSoGCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMaSoGCSCompleted(this, new getMaSoGCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CountMaSoGCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CountMaSoGCS() {
            object[] results = this.Invoke("CountMaSoGCS", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void CountMaSoGCSAsync() {
            this.CountMaSoGCSAsync(null);
        }
        
        /// <remarks/>
        public void CountMaSoGCSAsync(object userState) {
            if ((this.CountMaSoGCSOperationCompleted == null)) {
                this.CountMaSoGCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCountMaSoGCSOperationCompleted);
            }
            this.InvokeAsync("CountMaSoGCS", new object[0], this.CountMaSoGCSOperationCompleted, userState);
        }
        
        private void OnCountMaSoGCSOperationCompleted(object arg) {
            if ((this.CountMaSoGCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CountMaSoGCSCompleted(this, new CountMaSoGCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertDSachSo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertDSachSo(System.Data.DataSet dsDSachMoi) {
            object[] results = this.Invoke("InsertDSachSo", new object[] {
                        dsDSachMoi});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertDSachSoAsync(System.Data.DataSet dsDSachMoi) {
            this.InsertDSachSoAsync(dsDSachMoi, null);
        }
        
        /// <remarks/>
        public void InsertDSachSoAsync(System.Data.DataSet dsDSachMoi, object userState) {
            if ((this.InsertDSachSoOperationCompleted == null)) {
                this.InsertDSachSoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertDSachSoOperationCompleted);
            }
            this.InvokeAsync("InsertDSachSo", new object[] {
                        dsDSachMoi}, this.InsertDSachSoOperationCompleted, userState);
        }
        
        private void OnInsertDSachSoOperationCompleted(object arg) {
            if ((this.InsertDSachSoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertDSachSoCompleted(this, new InsertDSachSoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteMaSoGCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteMaSoGCS(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID) {
            object[] results = this.Invoke("DeleteMaSoGCS", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam,
                        strTenDNhap,
                        lngCurrentLibID,
                        lngWorkflowID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteMaSoGCSAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID) {
            this.DeleteMaSoGCSAsync(strMaDViQLy, strMaSoGCS, i16Ky, i16Thang, i16Nam, strTenDNhap, lngCurrentLibID, lngWorkflowID, null);
        }
        
        /// <remarks/>
        public void DeleteMaSoGCSAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, object userState) {
            if ((this.DeleteMaSoGCSOperationCompleted == null)) {
                this.DeleteMaSoGCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteMaSoGCSOperationCompleted);
            }
            this.InvokeAsync("DeleteMaSoGCS", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam,
                        strTenDNhap,
                        lngCurrentLibID,
                        lngWorkflowID}, this.DeleteMaSoGCSOperationCompleted, userState);
        }
        
        private void OnDeleteMaSoGCSOperationCompleted(object arg) {
            if ((this.DeleteMaSoGCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteMaSoGCSCompleted(this, new DeleteMaSoGCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSoGCS_Queue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSoGCS_Queue() {
            object[] results = this.Invoke("getSoGCS_Queue", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getSoGCS_QueueAsync() {
            this.getSoGCS_QueueAsync(null);
        }
        
        /// <remarks/>
        public void getSoGCS_QueueAsync(object userState) {
            if ((this.getSoGCS_QueueOperationCompleted == null)) {
                this.getSoGCS_QueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSoGCS_QueueOperationCompleted);
            }
            this.InvokeAsync("getSoGCS_Queue", new object[0], this.getSoGCS_QueueOperationCompleted, userState);
        }
        
        private void OngetSoGCS_QueueOperationCompleted(object arg) {
            if ((this.getSoGCS_QueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSoGCS_QueueCompleted(this, new getSoGCS_QueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLogByNumOfRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLogByNumOfRecord(int intNumRecord) {
            object[] results = this.Invoke("getLogByNumOfRecord", new object[] {
                        intNumRecord});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getLogByNumOfRecordAsync(int intNumRecord) {
            this.getLogByNumOfRecordAsync(intNumRecord, null);
        }
        
        /// <remarks/>
        public void getLogByNumOfRecordAsync(int intNumRecord, object userState) {
            if ((this.getLogByNumOfRecordOperationCompleted == null)) {
                this.getLogByNumOfRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogByNumOfRecordOperationCompleted);
            }
            this.InvokeAsync("getLogByNumOfRecord", new object[] {
                        intNumRecord}, this.getLogByNumOfRecordOperationCompleted, userState);
        }
        
        private void OngetLogByNumOfRecordOperationCompleted(object arg) {
            if ((this.getLogByNumOfRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogByNumOfRecordCompleted(this, new getLogByNumOfRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLogBySubdivisionID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLogBySubdivisionID(string SubdivisionID, int intNumRecord) {
            object[] results = this.Invoke("getLogBySubdivisionID", new object[] {
                        SubdivisionID,
                        intNumRecord});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getLogBySubdivisionIDAsync(string SubdivisionID, int intNumRecord) {
            this.getLogBySubdivisionIDAsync(SubdivisionID, intNumRecord, null);
        }
        
        /// <remarks/>
        public void getLogBySubdivisionIDAsync(string SubdivisionID, int intNumRecord, object userState) {
            if ((this.getLogBySubdivisionIDOperationCompleted == null)) {
                this.getLogBySubdivisionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogBySubdivisionIDOperationCompleted);
            }
            this.InvokeAsync("getLogBySubdivisionID", new object[] {
                        SubdivisionID,
                        intNumRecord}, this.getLogBySubdivisionIDOperationCompleted, userState);
        }
        
        private void OngetLogBySubdivisionIDOperationCompleted(object arg) {
            if ((this.getLogBySubdivisionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogBySubdivisionIDCompleted(this, new getLogBySubdivisionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getLogByBookID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getLogByBookID(string SubdivisionID, string strMaSoGCS, int intNumRecord) {
            object[] results = this.Invoke("getLogByBookID", new object[] {
                        SubdivisionID,
                        strMaSoGCS,
                        intNumRecord});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getLogByBookIDAsync(string SubdivisionID, string strMaSoGCS, int intNumRecord) {
            this.getLogByBookIDAsync(SubdivisionID, strMaSoGCS, intNumRecord, null);
        }
        
        /// <remarks/>
        public void getLogByBookIDAsync(string SubdivisionID, string strMaSoGCS, int intNumRecord, object userState) {
            if ((this.getLogByBookIDOperationCompleted == null)) {
                this.getLogByBookIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLogByBookIDOperationCompleted);
            }
            this.InvokeAsync("getLogByBookID", new object[] {
                        SubdivisionID,
                        strMaSoGCS,
                        intNumRecord}, this.getLogByBookIDOperationCompleted, userState);
        }
        
        private void OngetLogByBookIDOperationCompleted(object arg) {
            if ((this.getLogByBookIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getLogByBookIDCompleted(this, new getLogByBookIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteByMaSoGCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteByMaSoGCS(string strMaDViQLy, string strMaSoGCS) {
            object[] results = this.Invoke("DeleteByMaSoGCS", new object[] {
                        strMaDViQLy,
                        strMaSoGCS});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteByMaSoGCSAsync(string strMaDViQLy, string strMaSoGCS) {
            this.DeleteByMaSoGCSAsync(strMaDViQLy, strMaSoGCS, null);
        }
        
        /// <remarks/>
        public void DeleteByMaSoGCSAsync(string strMaDViQLy, string strMaSoGCS, object userState) {
            if ((this.DeleteByMaSoGCSOperationCompleted == null)) {
                this.DeleteByMaSoGCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteByMaSoGCSOperationCompleted);
            }
            this.InvokeAsync("DeleteByMaSoGCS", new object[] {
                        strMaDViQLy,
                        strMaSoGCS}, this.DeleteByMaSoGCSOperationCompleted, userState);
        }
        
        private void OnDeleteByMaSoGCSOperationCompleted(object arg) {
            if ((this.DeleteByMaSoGCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteByMaSoGCSCompleted(this, new DeleteByMaSoGCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteByLogID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteByLogID(string strMaDViQLy, long lngLogID) {
            object[] results = this.Invoke("DeleteByLogID", new object[] {
                        strMaDViQLy,
                        lngLogID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteByLogIDAsync(string strMaDViQLy, long lngLogID) {
            this.DeleteByLogIDAsync(strMaDViQLy, lngLogID, null);
        }
        
        /// <remarks/>
        public void DeleteByLogIDAsync(string strMaDViQLy, long lngLogID, object userState) {
            if ((this.DeleteByLogIDOperationCompleted == null)) {
                this.DeleteByLogIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteByLogIDOperationCompleted);
            }
            this.InvokeAsync("DeleteByLogID", new object[] {
                        strMaDViQLy,
                        lngLogID}, this.DeleteByLogIDOperationCompleted, userState);
        }
        
        private void OnDeleteByLogIDOperationCompleted(object arg) {
            if ((this.DeleteByLogIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteByLogIDCompleted(this, new DeleteByLogIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvoiceData_ForCalculation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getInvoiceData_ForCalculation(string strMaDViQLy, short ky, short thang, short nam) {
            object[] results = this.Invoke("getInvoiceData_ForCalculation", new object[] {
                        strMaDViQLy,
                        ky,
                        thang,
                        nam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getInvoiceData_ForCalculationAsync(string strMaDViQLy, short ky, short thang, short nam) {
            this.getInvoiceData_ForCalculationAsync(strMaDViQLy, ky, thang, nam, null);
        }
        
        /// <remarks/>
        public void getInvoiceData_ForCalculationAsync(string strMaDViQLy, short ky, short thang, short nam, object userState) {
            if ((this.getInvoiceData_ForCalculationOperationCompleted == null)) {
                this.getInvoiceData_ForCalculationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvoiceData_ForCalculationOperationCompleted);
            }
            this.InvokeAsync("getInvoiceData_ForCalculation", new object[] {
                        strMaDViQLy,
                        ky,
                        thang,
                        nam}, this.getInvoiceData_ForCalculationOperationCompleted, userState);
        }
        
        private void OngetInvoiceData_ForCalculationOperationCompleted(object arg) {
            if ((this.getInvoiceData_ForCalculationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvoiceData_ForCalculationCompleted(this, new getInvoiceData_ForCalculationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInvoiceData_ForCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getInvoiceData_ForCancel(string strMaDViQLy, short ky, short thang, short nam) {
            object[] results = this.Invoke("getInvoiceData_ForCancel", new object[] {
                        strMaDViQLy,
                        ky,
                        thang,
                        nam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getInvoiceData_ForCancelAsync(string strMaDViQLy, short ky, short thang, short nam) {
            this.getInvoiceData_ForCancelAsync(strMaDViQLy, ky, thang, nam, null);
        }
        
        /// <remarks/>
        public void getInvoiceData_ForCancelAsync(string strMaDViQLy, short ky, short thang, short nam, object userState) {
            if ((this.getInvoiceData_ForCancelOperationCompleted == null)) {
                this.getInvoiceData_ForCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInvoiceData_ForCancelOperationCompleted);
            }
            this.InvokeAsync("getInvoiceData_ForCancel", new object[] {
                        strMaDViQLy,
                        ky,
                        thang,
                        nam}, this.getInvoiceData_ForCancelOperationCompleted, userState);
        }
        
        private void OngetInvoiceData_ForCancelOperationCompleted(object arg) {
            if ((this.getInvoiceData_ForCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInvoiceData_ForCancelCompleted(this, new getInvoiceData_ForCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelInvoiceCalculation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelInvoiceCalculation(string strMaDViQLy, string[] strMaSoGCs, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, short i16Ky, short i16Thang, short i16Nam) {
            object[] results = this.Invoke("CancelInvoiceCalculation", new object[] {
                        strMaDViQLy,
                        strMaSoGCs,
                        strTenDNhap,
                        lngCurrentLibID,
                        lngWorkflowID,
                        i16Ky,
                        i16Thang,
                        i16Nam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelInvoiceCalculationAsync(string strMaDViQLy, string[] strMaSoGCs, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, short i16Ky, short i16Thang, short i16Nam) {
            this.CancelInvoiceCalculationAsync(strMaDViQLy, strMaSoGCs, strTenDNhap, lngCurrentLibID, lngWorkflowID, i16Ky, i16Thang, i16Nam, null);
        }
        
        /// <remarks/>
        public void CancelInvoiceCalculationAsync(string strMaDViQLy, string[] strMaSoGCs, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, short i16Ky, short i16Thang, short i16Nam, object userState) {
            if ((this.CancelInvoiceCalculationOperationCompleted == null)) {
                this.CancelInvoiceCalculationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelInvoiceCalculationOperationCompleted);
            }
            this.InvokeAsync("CancelInvoiceCalculation", new object[] {
                        strMaDViQLy,
                        strMaSoGCs,
                        strTenDNhap,
                        lngCurrentLibID,
                        lngWorkflowID,
                        i16Ky,
                        i16Thang,
                        i16Nam}, this.CancelInvoiceCalculationOperationCompleted, userState);
        }
        
        private void OnCancelInvoiceCalculationOperationCompleted(object arg) {
            if ((this.CancelInvoiceCalculationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelInvoiceCalculationCompleted(this, new CancelInvoiceCalculationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInvoice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetInvoice(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            object[] results = this.Invoke("GetInvoice", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetInvoiceAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            this.GetInvoiceAsync(strMaDViQLy, strMaSoGCS, i16Ky, i16Thang, i16Nam, null);
        }
        
        /// <remarks/>
        public void GetInvoiceAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, object userState) {
            if ((this.GetInvoiceOperationCompleted == null)) {
                this.GetInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInvoiceOperationCompleted);
            }
            this.InvokeAsync("GetInvoice", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam}, this.GetInvoiceOperationCompleted, userState);
        }
        
        private void OnGetInvoiceOperationCompleted(object arg) {
            if ((this.GetInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInvoiceCompleted(this, new GetInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSoGCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSoGCS(string strMaDViQLy, short i16Ky, short i16Thang, short i16Nam) {
            object[] results = this.Invoke("GetSoGCS", new object[] {
                        strMaDViQLy,
                        i16Ky,
                        i16Thang,
                        i16Nam});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSoGCSAsync(string strMaDViQLy, short i16Ky, short i16Thang, short i16Nam) {
            this.GetSoGCSAsync(strMaDViQLy, i16Ky, i16Thang, i16Nam, null);
        }
        
        /// <remarks/>
        public void GetSoGCSAsync(string strMaDViQLy, short i16Ky, short i16Thang, short i16Nam, object userState) {
            if ((this.GetSoGCSOperationCompleted == null)) {
                this.GetSoGCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSoGCSOperationCompleted);
            }
            this.InvokeAsync("GetSoGCS", new object[] {
                        strMaDViQLy,
                        i16Ky,
                        i16Thang,
                        i16Nam}, this.GetSoGCSOperationCompleted, userState);
        }
        
        private void OnGetSoGCSOperationCompleted(object arg) {
            if ((this.GetSoGCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSoGCSCompleted(this, new GetSoGCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoaiDoiTuong {
        
        /// <remarks/>
        DIEM_DO,
        
        /// <remarks/>
        SO_GCS,
        
        /// <remarks/>
        KHACH_HANG,
        
        /// <remarks/>
        HOP_DONG,
        
        /// <remarks/>
        PHIEU_THU,
        
        /// <remarks/>
        BBAN_APGIA,
        
        /// <remarks/>
        BBAN_GTHU,
        
        /// <remarks/>
        BBAN_QTOAN,
        
        /// <remarks/>
        BBAN_TRTH,
        
        /// <remarks/>
        YEU_CAU,
        
        /// <remarks/>
        CONG_TO,
        
        /// <remarks/>
        TU,
        
        /// <remarks/>
        TI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void KillSelfNewCompletedEventHandler(object sender, KillSelfNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KillSelfNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KillSelfNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strTimeStamp {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getMaSoGCSCompletedEventHandler(object sender, getMaSoGCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMaSoGCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMaSoGCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CountMaSoGCSCompletedEventHandler(object sender, CountMaSoGCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CountMaSoGCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CountMaSoGCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertDSachSoCompletedEventHandler(object sender, InsertDSachSoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertDSachSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertDSachSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteMaSoGCSCompletedEventHandler(object sender, DeleteMaSoGCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteMaSoGCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteMaSoGCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getSoGCS_QueueCompletedEventHandler(object sender, getSoGCS_QueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSoGCS_QueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSoGCS_QueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLogByNumOfRecordCompletedEventHandler(object sender, getLogByNumOfRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLogByNumOfRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogByNumOfRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLogBySubdivisionIDCompletedEventHandler(object sender, getLogBySubdivisionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLogBySubdivisionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogBySubdivisionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getLogByBookIDCompletedEventHandler(object sender, getLogByBookIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getLogByBookIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getLogByBookIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteByMaSoGCSCompletedEventHandler(object sender, DeleteByMaSoGCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteByMaSoGCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteByMaSoGCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteByLogIDCompletedEventHandler(object sender, DeleteByLogIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteByLogIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteByLogIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getInvoiceData_ForCalculationCompletedEventHandler(object sender, getInvoiceData_ForCalculationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvoiceData_ForCalculationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvoiceData_ForCalculationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getInvoiceData_ForCancelCompletedEventHandler(object sender, getInvoiceData_ForCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInvoiceData_ForCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInvoiceData_ForCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CancelInvoiceCalculationCompletedEventHandler(object sender, CancelInvoiceCalculationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelInvoiceCalculationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelInvoiceCalculationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetInvoiceCompletedEventHandler(object sender, GetInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSoGCSCompletedEventHandler(object sender, GetSoGCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSoGCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSoGCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591