//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISerManagementServer")]
public interface ISerManagementServer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/getConnectString", ReplyAction="http://tempuri.org/ISerManagementServer/getConnectStringResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string getConnectString();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/insertServer", ReplyAction="http://tempuri.org/ISerManagementServer/insertServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string insertServer(string strIP, string strConnectAddress);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/updateServer", ReplyAction="http://tempuri.org/ISerManagementServer/updateServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string updateServer(string strIP, string strConnectAddress);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/deleteServer", ReplyAction="http://tempuri.org/ISerManagementServer/deleteServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string deleteServer(string strIP);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/deleteAllServer", ReplyAction="http://tempuri.org/ISerManagementServer/deleteAllServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string deleteAllServer();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/getListServer", ReplyAction="http://tempuri.org/ISerManagementServer/getListServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getListServer();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISerManagementServer/getServer", ReplyAction="http://tempuri.org/ISerManagementServer/getServerResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getServer(string strIP);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISerManagementServerChannel : ISerManagementServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SerManagementServerClient : System.ServiceModel.ClientBase<ISerManagementServer>, ISerManagementServer
{
    
    public SerManagementServerClient()
    {
    }
    
    public SerManagementServerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SerManagementServerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SerManagementServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SerManagementServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string getConnectString()
    {
        return base.Channel.getConnectString();
    }
    
    public string insertServer(string strIP, string strConnectAddress)
    {
        return base.Channel.insertServer(strIP, strConnectAddress);
    }
    
    public string updateServer(string strIP, string strConnectAddress)
    {
        return base.Channel.updateServer(strIP, strConnectAddress);
    }
    
    public string deleteServer(string strIP)
    {
        return base.Channel.deleteServer(strIP);
    }
    
    public string deleteAllServer()
    {
        return base.Channel.deleteAllServer();
    }
    
    public System.Data.DataSet getListServer()
    {
        return base.Channel.getListServer();
    }
    
    public System.Data.DataSet getServer(string strIP)
    {
        return base.Channel.getServer(strIP);
    }
}
