//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data;



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceTinhHDon")]
public interface IServiceTinhHDon
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getMaSoGCS", ReplyAction="http://tempuri.org/IServiceTinhHDon/getMaSoGCSResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getMaSoGCS();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/InsertDSachSo", ReplyAction="http://tempuri.org/IServiceTinhHDon/InsertDSachSoResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    bool InsertDSachSo(System.Data.DataSet dsDSachMoi);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/DeleteMaSoGCS", ReplyAction="http://tempuri.org/IServiceTinhHDon/DeleteMaSoGCSResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    bool DeleteMaSoGCS();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/CountMaSoGCS", ReplyAction="http://tempuri.org/IServiceTinhHDon/CountMaSoGCSResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    long CountMaSoGCS();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getLogByNumOfRecord", ReplyAction="http://tempuri.org/IServiceTinhHDon/getLogByNumOfRecordResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getLogByNumOfRecord(int intNumRecord);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getLogBySubdivisionID", ReplyAction="http://tempuri.org/IServiceTinhHDon/getLogBySubdivisionIDResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getLogBySubdivisionID(string SubdivisionID, int intNumRecord);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getLogByBookID", ReplyAction="http://tempuri.org/IServiceTinhHDon/getLogByBookIDResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getLogByBookID(string SubdivisionID, string strMaSoGCS, int intNumRecord);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getInvoiceData_ForCancel", ReplyAction="http://tempuri.org/IServiceTinhHDon/getInvoiceData_ForCancelResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getInvoiceData_ForCancel(string strMaDViQLy, short ky, short thang, short nam);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/getInvoiceData_ForCalculation", ReplyAction="http://tempuri.org/IServiceTinhHDon/getInvoiceData_ForCalculationResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Data.DataSet getInvoiceData_ForCalculation(string strMaDViQLy, short ky, short thang, short nam);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/CancelInvoiceCalculation", ReplyAction="http://tempuri.org/IServiceTinhHDon/CancelInvoiceCalculationResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string CancelInvoiceCalculation(string strMaDViQLy, string[] strMaSoGCs, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, short i16Ky, short i16Thang, short i16Nam);
    
    // CODEGEN: Parameter 'GetDataUsingDataContractResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTinhHDon/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceTinhHDon/GetDataUsingDataContractResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetDataUsingDataContractResponse GetDataUsingDataContract(GetDataUsingDataContractRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFApplicationServer")]
public partial class CompositeType
{
    
    private bool boolValueField;
    
    private bool boolValueFieldSpecified;
    
    private string stringValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool BoolValue
    {
        get
        {
            return this.boolValueField;
        }
        set
        {
            this.boolValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BoolValueSpecified
    {
        get
        {
            return this.boolValueFieldSpecified;
        }
        set
        {
            this.boolValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string StringValue
    {
        get
        {
            return this.stringValueField;
        }
        set
        {
            this.stringValueField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CompositeType composite;
    
    public GetDataUsingDataContractRequest()
    {
    }
    
    public GetDataUsingDataContractRequest(CompositeType composite)
    {
        this.composite = composite;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetDataUsingDataContractResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public CompositeType GetDataUsingDataContractResult;
    
    public GetDataUsingDataContractResponse()
    {
    }
    
    public GetDataUsingDataContractResponse(CompositeType GetDataUsingDataContractResult)
    {
        this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceTinhHDonChannel : IServiceTinhHDon, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceTinhHDonClient : System.ServiceModel.ClientBase<IServiceTinhHDon>, IServiceTinhHDon
{
    
    public ServiceTinhHDonClient()
    {
    }
    
    public ServiceTinhHDonClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceTinhHDonClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTinhHDonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceTinhHDonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Data.DataSet getMaSoGCS()
    {
        return base.Channel.getMaSoGCS();
    }
    
    public bool InsertDSachSo(System.Data.DataSet dsDSachMoi)
    {
        return base.Channel.InsertDSachSo(dsDSachMoi);
    }
    
    public bool DeleteMaSoGCS()
    {
        return base.Channel.DeleteMaSoGCS();
    }
    
    public long CountMaSoGCS()
    {
        return base.Channel.CountMaSoGCS();
    }
    
    public System.Data.DataSet getLogByNumOfRecord(int intNumRecord)
    {
        return base.Channel.getLogByNumOfRecord(intNumRecord);
    }
    
    public System.Data.DataSet getLogBySubdivisionID(string SubdivisionID, int intNumRecord)
    {
        return base.Channel.getLogBySubdivisionID(SubdivisionID, intNumRecord);
    }
    
    public System.Data.DataSet getLogByBookID(string SubdivisionID, string strMaSoGCS, int intNumRecord)
    {
        return base.Channel.getLogByBookID(SubdivisionID, strMaSoGCS, intNumRecord);
    }
    
    public System.Data.DataSet getInvoiceData_ForCancel(string strMaDViQLy, short ky, short thang, short nam)
    {
        return base.Channel.getInvoiceData_ForCancel(strMaDViQLy, ky, thang, nam);
    }
    
    public System.Data.DataSet getInvoiceData_ForCalculation(string strMaDViQLy, short ky, short thang, short nam)
    {
        return base.Channel.getInvoiceData_ForCalculation(strMaDViQLy, ky, thang, nam);
    }
    
    public string CancelInvoiceCalculation(string strMaDViQLy, string[] strMaSoGCs, string strTenDNhap, long lngCurrentLibID, long lngWorkflowID, short i16Ky, short i16Thang, short i16Nam)
    {
        return base.Channel.CancelInvoiceCalculation(strMaDViQLy, strMaSoGCs, strTenDNhap, lngCurrentLibID, lngWorkflowID, i16Ky, i16Thang, i16Nam);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetDataUsingDataContractResponse IServiceTinhHDon.GetDataUsingDataContract(GetDataUsingDataContractRequest request)
    {
        return base.Channel.GetDataUsingDataContract(request);
    }
    
    public CompositeType GetDataUsingDataContract(CompositeType composite)
    {
        GetDataUsingDataContractRequest inValue = new GetDataUsingDataContractRequest();
        inValue.composite = composite;
        GetDataUsingDataContractResponse retVal = ((IServiceTinhHDon)(this)).GetDataUsingDataContract(inValue);
        return retVal.GetDataUsingDataContractResult;
    }
}
