//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BillingImplementation.Service_DebugTHD {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_DebugTHDSoap", Namespace="http://tempuri.org/")]
    public partial class Service_DebugTHD : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback checkPhuGhepTong_ServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCustomerDataReading_ServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStaticCatalogDataReading_ServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_DebugTHD() {
            this.Url = global::BillingImplementation.Properties.Settings.Default.BillingImplementation_Service_DebugTHD_Service_DebugTHD;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event checkPhuGhepTong_ServiceCompletedEventHandler checkPhuGhepTong_ServiceCompleted;
        
        /// <remarks/>
        public event getCustomerDataReading_ServiceCompletedEventHandler getCustomerDataReading_ServiceCompleted;
        
        /// <remarks/>
        public event getStaticCatalogDataReading_ServiceCompletedEventHandler getStaticCatalogDataReading_ServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/checkPhuGhepTong_Service", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string checkPhuGhepTong_Service(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            object[] results = this.Invoke("checkPhuGhepTong_Service", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void checkPhuGhepTong_ServiceAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            this.checkPhuGhepTong_ServiceAsync(strMaDViQLy, strMaSoGCS, i16Ky, i16Thang, i16Nam, null);
        }
        
        /// <remarks/>
        public void checkPhuGhepTong_ServiceAsync(string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, object userState) {
            if ((this.checkPhuGhepTong_ServiceOperationCompleted == null)) {
                this.checkPhuGhepTong_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OncheckPhuGhepTong_ServiceOperationCompleted);
            }
            this.InvokeAsync("checkPhuGhepTong_Service", new object[] {
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam}, this.checkPhuGhepTong_ServiceOperationCompleted, userState);
        }
        
        private void OncheckPhuGhepTong_ServiceOperationCompleted(object arg) {
            if ((this.checkPhuGhepTong_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.checkPhuGhepTong_ServiceCompleted(this, new checkPhuGhepTong_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerDataReading_Service", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCustomerDataReading_Service(ref System.Data.DataSet dsCustomerData, string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            object[] results = this.Invoke("getCustomerDataReading_Service", new object[] {
                        dsCustomerData,
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam});
            dsCustomerData = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCustomerDataReading_ServiceAsync(System.Data.DataSet dsCustomerData, string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam) {
            this.getCustomerDataReading_ServiceAsync(dsCustomerData, strMaDViQLy, strMaSoGCS, i16Ky, i16Thang, i16Nam, null);
        }
        
        /// <remarks/>
        public void getCustomerDataReading_ServiceAsync(System.Data.DataSet dsCustomerData, string strMaDViQLy, string strMaSoGCS, short i16Ky, short i16Thang, short i16Nam, object userState) {
            if ((this.getCustomerDataReading_ServiceOperationCompleted == null)) {
                this.getCustomerDataReading_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerDataReading_ServiceOperationCompleted);
            }
            this.InvokeAsync("getCustomerDataReading_Service", new object[] {
                        dsCustomerData,
                        strMaDViQLy,
                        strMaSoGCS,
                        i16Ky,
                        i16Thang,
                        i16Nam}, this.getCustomerDataReading_ServiceOperationCompleted, userState);
        }
        
        private void OngetCustomerDataReading_ServiceOperationCompleted(object arg) {
            if ((this.getCustomerDataReading_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerDataReading_ServiceCompleted(this, new getCustomerDataReading_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getStaticCatalogDataReading_Service", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getStaticCatalogDataReading_Service(ref System.Data.DataSet dsStaticCatalog) {
            object[] results = this.Invoke("getStaticCatalogDataReading_Service", new object[] {
                        dsStaticCatalog});
            dsStaticCatalog = ((System.Data.DataSet)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getStaticCatalogDataReading_ServiceAsync(System.Data.DataSet dsStaticCatalog) {
            this.getStaticCatalogDataReading_ServiceAsync(dsStaticCatalog, null);
        }
        
        /// <remarks/>
        public void getStaticCatalogDataReading_ServiceAsync(System.Data.DataSet dsStaticCatalog, object userState) {
            if ((this.getStaticCatalogDataReading_ServiceOperationCompleted == null)) {
                this.getStaticCatalogDataReading_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStaticCatalogDataReading_ServiceOperationCompleted);
            }
            this.InvokeAsync("getStaticCatalogDataReading_Service", new object[] {
                        dsStaticCatalog}, this.getStaticCatalogDataReading_ServiceOperationCompleted, userState);
        }
        
        private void OngetStaticCatalogDataReading_ServiceOperationCompleted(object arg) {
            if ((this.getStaticCatalogDataReading_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStaticCatalogDataReading_ServiceCompleted(this, new getStaticCatalogDataReading_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void checkPhuGhepTong_ServiceCompletedEventHandler(object sender, checkPhuGhepTong_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class checkPhuGhepTong_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal checkPhuGhepTong_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getCustomerDataReading_ServiceCompletedEventHandler(object sender, getCustomerDataReading_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerDataReading_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCustomerDataReading_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsCustomerData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getStaticCatalogDataReading_ServiceCompletedEventHandler(object sender, getStaticCatalogDataReading_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStaticCatalogDataReading_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStaticCatalogDataReading_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet dsStaticCatalog {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591